### PR TITLE
fix(devcontainer): parse user in multi-stage builds

### LINKED ISSUE #231: devcontainer: support multi-stage build with dangling build stage
Currently, building a devcontainer that specifies a multi-stage build with a "dangling" `FROM image AS alias` fails.

Example integration test that reproduces the issue:

```
func TestBuildFromDevcontainerWithMultistage(t *testing.T) {
	t.Parallel()

	// Ensures that a Git repository with a devcontainer.json is cloned and built.
	srv := createGitServer(t, gitServerOptions{
		files: map[string]string{
			"devcontainer.json": `{
				"name": "Test",
				"build": {
					"dockerfile": "Dockerfile"
				},
			}`,
			"Dockerfile": fmt.Sprintf(`FROM %s as a
RUN date > /root/date.txt
FROM %s as b
COPY --from=a /root/date.txt /date.txt`, testImageUbuntu, testImageUbuntu),
		},
	})
	ctr, err := runEnvbuilder(t, options{env: []string{
		envbuilderEnv("GIT_URL", srv.URL),
	}})
	require.NoError(t, err)

	output := execContainer(t, ctr, "cat /date.txt")
	require.NotEmpty(t, strings.TrimSpace(output))
}
```

The above test fails with the following error:

```
--- FAIL: TestBuildFromDevcontainerWithMultistage (0.39s)
    /home/coder/src/coder/envbuilder/integration/integration_test.go:1207: "\x1b[1menvbuilder\x1b[22m - Build development environments from repositories in a container"
    /home/coder/src/coder/envbuilder/integration/integration_test.go:1207: "#1: 📦 Cloning \x1b[36mhttp://127.0.0.1:39405\x1b[0m to \x1b[36m/workspaces/empty\x1b[0m..."
    /home/coder/src/coder/envbuilder/integration/integration_test.go:1207: "#1: 👤 Using no authentication!"
    /home/coder/src/coder/envbuilder/integration/integration_test.go:1207: "#1: 📦 Cloned repository! [9.601971ms]"
    /home/coder/src/coder/envbuilder/integration/integration_test.go:1207: "error: compile devcontainer.json: parse image from dockerfile: parse image ref \"localhost:5000/envbuilder-test-ubuntu:latest as b\": could not parse reference: localhost:5000/envbuilder-test-ubuntu:latest as b"
    /home/coder/src/coder/envbuilder/integration/integration_test.go:526: 
        	Error Trace:	/home/coder/src/coder/envbuilder/integration/integration_test.go:526
        	Error:      	Received unexpected error:
        	            	error: compile devcontainer.json: parse image from dockerfile: parse image ref "localhost:5000/envbuilder-test-ubuntu:latest as b": could not parse reference: localhost:5000/envbuilder-test-ubuntu:latest as b
        	Test:       	TestBuildFromDevcontainerWithMultistage
```

It looks like we need to handle this in `devcontainer.ImageFromDockerfile`.

Workaround: remove the dangling directive:

```
FROM image AS a
RUN thing
FROM anotherimage AS b
COPY --from=a /something /somewhere
```

becomes

```
FROM image AS a
RUN thing
FROM anotherimage
COPY --from=a /something /somewhere
```

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #231

---

There's some more assumption and parsing fixing I want to do in `devcontainer` package, but I'll make other PRs for those.

### CODE REVIEW

File: devcontainer/devcontainer.go [hunk 1]
```diff
@@ -313,17 +308,82 @@ func (s *Spec) compileFeatures(fs billy.Filesystem, devcontainerDir, scratchDir
...
+		ref, err := name.ParseReference(strings.TrimSpace(stage.BaseName))
+		if err != nil {
+			return "", fmt.Errorf("parse image ref %q: %w", stage.BaseName, err)
+		}
+		user, err := UserFromImage(ref)
+		if err != nil {
+			return "", fmt.Errorf("user from image %s: %w", ref.Name(), err)
+		}
+		return user, nil
 	}
```
Comment (johnstcn) [inline devcontainer/devcontainer.go:384]: It's unfortunate to have to reach out to the remote repo to get the image manifest, but it looks like this is our only option since there's no local Docker daemon to ask :(

File: devcontainer/devcontainer.go [hunk 2]
```diff
@@ -313,17 +308,82 @@ func (s *Spec) compileFeatures(fs billy.Filesystem, devcontainerDir, scratchDir
...
-		return strings.TrimSpace(strings.TrimPrefix(line, "USER "))
+
+		if user, ok := stageUser[stage]; ok {
+			return user.User, nil
+		}
+
+		// If we reach the scratch stage, we can't determine the user.
+		if stage.BaseName == "scratch" {
+			return "", nil
+		}
```
Comment (johnstcn) [inline devcontainer/devcontainer.go:362]: Confirmed that building `FROM scratch` results in a manifest with `User: ""`.

**Review by johnstcn — APPROVED** [review]
Nice work! A couple of nits but nothing blocking from me.

**Review by mtojek — APPROVED** [review]
Nice job 👍 👍

File: devcontainer/devcontainer_test.go [hunk 3]
```diff
@@ -224,27 +218,156 @@ func TestImageFromDockerfile(t *testing.T) {
...
+			user    string
+		}{
+			{
+				name:    "Empty",
+				content: "FROM scratch",
+				user:    "",
+			},
+			{
+				name:    "User",
+				content: "FROM scrach\nUSER kyle",
```
[the remark this answers is not in the document]
Comment (mafredri) [reply devcontainer/devcontainer_test.go:261]: Good catch, thanks!

File: devcontainer/devcontainer_test.go [hunk 4]
```diff
@@ -224,27 +218,156 @@ func TestImageFromDockerfile(t *testing.T) {
...
+				user:    "kyle",
+			},
+			{
+				name:    "Env with default",
+				content: "FROM scratch\nENV MYUSER=maf\nUSER ${MYUSER}",
+				user:    "${MYUSER}", // This should be "maf" but the current implementation doesn't support this.
```
[the remark this answers is not in the document]
Comment (mafredri) [reply devcontainer/devcontainer_test.go:267]: https://github.com/coder/envbuilder/issues/344

File: devcontainer/devcontainer.go (hunk 1 above)
Comment (mafredri) [reply devcontainer/devcontainer.go:384]: I agree 😔, hopefully it's rarely needed.
