### PR TITLE
fix: extract folder correctly from repo URLs with trailing slash

### LINKED ISSUE #380: clone via branch does not create a project dir
from a prospective customer:

> when creating a devcontainer workspace via a direct repo link (e.g. https://github.com/org/repo-name), the envbuilder clones the repo into the `repo-name` directory, so you get `/workspaces/repo-name/`… , but when creating via a branch link (e.g. https://github.com/org/repo-name/#refs/heads/jon-coder), the envbuilder seems to clone the repo contents directly into `workspaces`, so you get `/workspaces/`…

this is blocking their devcontainer use-case with Coder, because their build/service scripts rely on the source path in order to work, so the project not being in `/workspaces/repo-name/` is breaking the services.

### PR DESCRIPTION
**Pull request by mafredri**
Closes #380
Closes coder/customers#690

### CODE REVIEW

File: options/defaults_test.go [hunk 1]
```diff
@@ -40,6 +40,41 @@ func TestDefaultWorkspaceFolder(t *testing.T) {
...
+			expected: "/workspaces/envbuilder",
+		},
+		{
+			name:     "trailing-x2",
+			gitURL:   "https://github.com/coder/envbuilder.git//",
+			expected: "/workspaces/envbuilder",
+		},
+		{
+			name:     "fragment-trailing",
+			gitURL:   "https://github.com/coder/envbuilder.git/#refs/heads/feature-branch",
```
Comment (mtojek) [inline options/defaults_test.go:55]: nit: maybe one more: `https://github.com/coder/envbuilder/#refs/heads/feature-branch` (no .git)

**Review by mtojek — APPROVED** [review]
