### PR TITLE
fix: refactor coder logger to allow flush without deadlock

### LINKED ISSUE #364: Defers run in `cmd/envbuilder` won't execute because Run performs `execve(2)`
Review: Even though we've fixed defers here, there's still `cmd/envbuilder` where e.g. `closeLogs` won't fire since we execve(2) after this.

_Originally posted by @mafredri in https://github.com/coder/envbuilder/pull/359#discussion_r1777477126_

### PR DESCRIPTION
**Pull request by mafredri**
- **Reapply "fix: add preExec to Run (#368)" (#371)**
- **fix: refactor coder logger to allow flush without deadlock**

Fixes #364

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
Refactor LGTM 👍

File: log/coder.go [hunk 1]
```diff
@@ -95,65 +100,67 @@ func initRPC(ctx context.Context, client *agentsdk.Client, l slog.Logger) (proto
...
+			ls.Enqueue(uid, agentsdk.Log{
+				CreatedAt: time.Now(),
+				Output:    fmt.Sprintf(msg, args...),
+				Level:     codersdk.LogLevel(l),
+			})
+		}, func() {
+			closeOnce.Do(func() {
+				// Trigger a flush and wait for logs to be sent.
+				ls.Flush(uid)
+				ctx, cancel := context.WithTimeout(ctx, logSendGracePeriod)
```
[the remark this answers is not in the document]
Comment (mafredri) [reply log/coder.go:152]: It's doable, but I feel their purpose is clearer as-is. We could actually make sendCtx not inherit function ctx instead.

File: log/coder.go [hunk 2]
```diff
@@ -74,13 +78,14 @@ func initClient(coderURL *url.URL, token string) *agentsdk.Client {
...
 	var err error
-	retryCtx, retryCancel := context.WithTimeout(context.Background(), rpcConnectTimeout)
+	retryCtx, retryCancel := context.WithTimeout(ctx, rpcConnectTimeout)
 	defer retryCancel()
 	attempts := 0
 	for r := retry.New(100*time.Millisecond, time.Second); r.Wait(retryCtx); {
 		attempts++
 		// Maximize compatibility.
 		c, err = client.ConnectRPC20(ctx)
+		l.Info(ctx, "Connecting to Coder", slog.F("attempt", attempts), slog.F("error", err))
```
[the remark this answers is not in the document]
Comment (mafredri) [reply log/coder.go:88]: Oh this was debugging I left in there 😅

File: cmd/envbuilder/main.go [hunk 3]
```diff
@@ -50,6 +56,10 @@ func envbuilderCmd() serpent.Command {
 				if err == nil {
 					o.Logger = log.Wrap(o.Logger, coderLog)
 					defer closeLogs()
+					preExec = append(preExec, func() {
+						o.Logger(log.LevelInfo, "Closing logs")
+						closeLogs()
```
Comment (dannykopping) [inline cmd/envbuilder/main.go:61]: `closeLogs()` will be called twice when the function exits; is that intentional?

File: log/coder.go [hunk 4]
```diff
@@ -44,18 +46,20 @@ func Coder(ctx context.Context, coderURL *url.URL, token string) (Func, func(),
 	}
 	if semver.Compare(semver.MajorMinor(bi.Version), minAgentAPIV2) < 0 {
 		metaLogger.Warn(ctx, "Detected Coder version incompatible with AgentAPI v2, falling back to deprecated API", slog.F("coder_version", bi.Version))
-		sendLogs, flushLogs := sendLogsV1(ctx, client, metaLogger.Named("send_logs_v1"))
-		return sendLogs, flushLogs, nil
+		logger, closer = sendLogsV1(ctx, client, metaLogger.Named("send_logs_v1"))
```
Comment (dannykopping) [inline log/coder.go:49]: Nice 👍 I found those previous names hard to reason about.

File: log/coder.go [hunk 5]
```diff
@@ -95,65 +99,67 @@ func initRPC(ctx context.Context, client *agentsdk.Client, l slog.Logger) (proto
...
+			if err := flushAndClose(ctx); err != nil {
 				l.Warn(ctx, "failed to flush logs", slog.Error(err))
 			}
 		}
 }
 
 // sendLogsV2 uses the v2 agent API to send logs. Only compatibile with coder versions >= 2.9.
-func sendLogsV2(ctx context.Context, dest agentsdk.LogDest, ls coderLogSender, l slog.Logger) (Func, func()) {
+func sendLogsV2(ctx context.Context, dest agentsdk.LogDest, ls coderLogSender, l slog.Logger) (logger Func, closer func()) {
+	sendCtx, sendCancel := context.WithCancel(ctx)
```
Comment (dannykopping) [inline log/coder.go:128]: Should `sendCancel` be deferred, too?

File: log/coder_internal_test.go [hunk 6]
```diff
@@ -221,6 +238,97 @@ func TestCoder(t *testing.T) {
 	})
 }
 
+//nolint:paralleltest // We need to replace a global timeout.
+func TestCoderRPCTimeout500MS(t *testing.T) {
```
Comment (dannykopping) [inline log/coder_internal_test.go:242]: Nit: do we have to include the timeout in the naming?

**Review by dannykopping — APPROVED** [review]

File: log/coder.go (hunk 5 above)
Comment (mafredri) [reply log/coder.go:128]: Nope, we want to keep this context alive until we've flushed or hit the timeout in the `closer` function.

File: log/coder_internal_test.go (hunk 6 above)
Comment (mafredri) [reply log/coder_internal_test.go:242]: We don't, wanted to be explicit since we set it in the parent and use it in subtests, so that it's clear you shouldn't modify it without taking all tests into account. I'll leave a comment instead.
